
// PHOTO CARD CONSTANTS
export const ADD_PHOTOCARD = "ADD_PHOTOCARD";
export const UPDATE_PHOTOCARD = "UPDATE_PHOTOCARD";
export const DELETE_PHOTOCARD = "DELETE_PHOTOCARD";
export const FETCH_PHOTOCARDS = "FETCH_PHOTOCARDS";

// COMMENTS
export const ADD_COMMENT = "ADD_COMMENT";

// LIKES
export const LIKE_PHOTO_ATTEMPT = "LIKE_PHOTO_ATTEMPT";
export const LIKE_PHOTO_SUCCESS = "LIKE_PHOTO_SUCCESS";
export const LIKE_PHOTO_FAILURE = "LIKE_PHOTO_FAILURE";

// USER

  // FETCH
  export const FETCH_USER = "FETCH_USER";
  export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

  // LOGIN
  export const USER_LOGIN_SUCCESS =  "USER_LOGIN_SUCCESS";
  export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
  export const USER_LOGIN_ATTEMPT = "USER_LOGIN_ATTEMPT";

  // SIGNUP
  export const USER_SIGNUP_ATTEMPT = "USER_SIGNUP_ATTEMPT";
  export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";
  export const USER_SIGNUP_SUCCESS =  "USER_SIGNUP_SUCCESS";

  // SIGNOUT
  export const USER_SIGNOUT = "USER_SIGNOUT";